### PR TITLE
Api setup

### PR DESCRIPTION
**Pull request by JBergen-Dev**
Add button does a POST action for song id. Id like to format the add button to appear inline with results but I'm having trouble with the css. I'm pushing now so everyone can start on their tasks which are dependent upon my task. unfortunately the extra line for the add button is making the 3rd result to overflow. I will fix all of this but the functionality is in place for Kirstyn to add song id's to database in the meantime.

image

### CODE REVIEW

**Comment by JBergen-Dev** [comment]
Go to https://developer.spotify.com/dashboard/ and login with Spotify account. From here, click create an app and fill out the required fields. Once your app is created, make a .env file with variables named SPOTIPY_CLIENT_ID and SPOTIPY_CLIENT_SECRET corresponding to your client ID and client secret on the app dashboard.

**Review by KinjalRele — COMMENTED** [review]
It looks good to me. Great work on getting the API working! 
Just add how to get the SPOTIPY_CLIENT_ID and SPOTIPY_CLIENT_SECRET keys to the readme.md and you are good to merge this in the main.

**Review by KinjalRele — APPROVED** [review]

**Review by Tactakon — APPROVED** [review]
Looks good

**Review by kfagnani — APPROVED** [review]
Y
E
S

G
O

J
O
H
N
!

**Pull request merged**
