### PR TITLE
Landing Page Header

### PR DESCRIPTION
**Pull request by kfagnani**
Created the header for the landing page (this is the page you land on when you would click Verge from google). Used bootstrap to make things easier and a lot more seamless. I plan to update older HTML pages with bootstrap as well. 
The Playlist, Passcode, Collaboration, etc buttons highlight when you hover over them.
The Sign In button also highlights when you hover over it. 

image
image

### CODE REVIEW

**Comment by kfagnani** [comment]
Made the changes per discussion with @KinjalRele. Attached the new photos below:

Navbar/header:
image

Navbar/header added to the landing page:
image

**Comment by kfagnani** [comment]
I created the Footer and attached it to the landing page - using Bootstrap.
The information nav links underline when you hover over them & the socials change color when hovered over. 
image

image

image

**Review by Tactakon — APPROVED** [review]
Looks good.

**Comment by KinjalRele** [comment]
The header and the footer look great!
While discussing the locations of this specific header and footer I think we missed that the header and the footer should also be there on the login and signup HTML files as well apart from our landing page, like in our Figma files.

**Pull request merged**
